# Generated by Django 2.2.7 on 2020-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20190822_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='voting_system',
            field=models.CharField(choices=[('condorcet', 'Condorcet'), ('schulze', 'Schulze, ordered list'), ('stv1', 'STV, single winner'), ('stv2', 'STV, two winners'), ('stv3', 'STV, three winners'), ('stv4', 'STV, four winners'), ('stv5', 'STV, five winners'), ('stv8', 'STV, eight winners'), ('stv10', 'STV, ten winners')], max_length=30, verbose_name='Voting system'),
        ),
    ]
