# Generated by Django 2.2.7 on 2020-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20200121_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='voting_system',
            field=models.CharField(choices=[('condorcet', 'Condorcet'), ('schulze', 'Schulze, ordered list'), ('stv1', 'STV, single winner'), ('stv2', 'STV, two winners'), ('stv3', 'STV, three winners'), ('stv4', 'STV, four winners'), ('stv5', 'STV, five winners'), ('stv6', 'STV, six winners'), ('stv8', 'STV, eight winners'), ('stv10', 'STV, ten winners')], max_length=30, verbose_name='Voting system'),
        ),
    ]
