# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20171201_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='stats_limit',
            new_name='results_limit',
        ),
    ]
