# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20180705_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='results_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many candidates will be publicly listed in the results of an election'),
        ),
    ]
