# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcontent',
            unique_together=set([('document', 'order')]),
        ),
    ]
