# Generated by Django 2.2.7 on 2020-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20190822_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
