# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0019_auto_20180117_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='power_when_cast',
        ),
    ]
