# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 21:10
from __future__ import unicode_literals

from django.db import migrations

from issue.models import Issue


def reprocess_issues(apps, schema_editor):
    # The order is actually very important here, because things like
    # predecessors and deprecated issues are determined by sequence.
    issues = Issue.objects.order_by('created')

    for issue in issues:
        issue.is_processed = False
        issue.save()
        issue.process()


def dummy_function(apps, schema_editor):
    # Only here to make reversing migrations possible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0020_remove_vote_power_when_cast'),
        ('issue', '0022_auto_20180123_2157'),
    ]

    operations = [
        migrations.RunPython(reprocess_issues, dummy_function)
    ]
