# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0005_polity_wranglers'),
        ('issue', '0022_auto_20180123_2157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('polity', 'issue_year', 'issue_num')]),
        ),
    ]
