# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0023_auto_20180325_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_adopted',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_proposed',
        ),
    ]
