# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0024_auto_20180325_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
