# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:48
from __future__ import unicode_literals

from django.db import migrations


def set_documentcontent_names(apps, schema_editor):
    DocumentContent = apps.get_model('issue', 'DocumentContent')
    for dc in DocumentContent.objects.select_related('document'):
        dc.name = dc.document.name
        dc.save()


def unset_documentcontent_names(apps, schema_editor):
    DocumentContent = apps.get_model('issue', 'DocumentContent')
    for dc in DocumentContent.objects.all():
        dc.name = u''
        dc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0025_documentcontent_name'),
    ]

    operations = [
        migrations.RunPython(
            set_documentcontent_names,
            unset_documentcontent_names
        ),
    ]
