# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0026_auto_20180325_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, help_text="An issue description is usually just a copy of the proposal's description, but you can customize it here if you so wish.", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(help_text='A great issue name expresses the essence of a proposal as briefly as possible.', max_length=128, verbose_name='Name'),
        ),
    ]
