# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0027_auto_20180325_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='special_process_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_process_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='status',
            field=models.CharField(choices=[(b'proposed', 'Proposed'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected'), (b'deprecated', 'Deprecated'), (b'retracted', 'Retracted')], default=b'proposed', max_length=32),
        ),
        migrations.AlterField(
            model_name='issue',
            name='special_process',
            field=models.CharField(blank=True, choices=[(b'accepted_at_assembly', 'Accepted at assembly'), (b'rejected_at_assembly', 'Rejected at assembly'), (b'retracted', 'Retracted')], default=b'', max_length=32, null=True, verbose_name='Special process'),
        ),
    ]
