# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0028_auto_20180605_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_year',
            field=models.IntegerField(null=True),
        ),
    ]
