# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='declaration_of_interests',
            field=models.TextField(blank=True, null=True, verbose_name='Declaration of interests'),
        ),
    ]
