# Generated by Django 2.2.6 on 2019-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190822_2006'),
        ('core', '0006_userprofile_phone'),
    ]

    operations = [
    ]
