# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20180117_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[(b'is', b'\xc3\x8dslenska'), (b'en', b'English')], default=b'en', max_length=6, verbose_name='Language'),
        ),
    ]
