# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_userprofile_email_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'profiles', verbose_name='Picture'),
        ),
    ]
