# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20180605_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_wanted',
            field=models.NullBooleanField(default=False, help_text='Whether to consent to receiving notifications via email.', verbose_name='Consent for sending email'),
        ),
    ]
