#!/usr/bin/env python

from core.models import *
import smtplib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header

mailserver = smtplib.SMTP_SSL('smtp.gmail.com')
mailserver.login('helgi.binary.is', 'temporarypass')

#email = 'helgi@piratar.is'
letter = open('letter', 'r').read()
#mailserver.sendmail('Helgi Hrafn Gunnarsson <helgi@piratar.is>', email, 'From: Helgi Hrafn Gunnarsson <helgi@piratar.is>\r\nTo: %s\r\n\r\n%s' % (email, letter))
#mailserver.sendmail('Helgi Hrafn Gunnarsson <helgi@piratar.is>', email, 'From: Helgi Hrafn Gunnarsson <helgi@piratar.is>\r\nTo: %s <%s>\r\n\r\n%s' % (name, email, letter))

election_ids = [1, 2, 3]

candidates = Candidate.objects.filter(election_id__in = election_ids)
user_ids = []
for candidate in candidates:
	user_ids.append(candidate.user_id)

users = User.objects.filter(id__in = user_ids)

for user in users:
	if user.email:
		if user.get_profile().displayname:
			name = user.get_profile().displayname
		else:
			name = user.username

		#print "%s <%s>" % (name, user.email)
		print user.email
		#time.sleep(3)
		#user.email = 'helgi@binary.is'
		#mailserver.sendmail('Helgi Hrafn Gunnarsson <helgi@piratar.is>', user.email, 'From: Helgi Hrafn Gunnarsson <helgi@piratar.is>\r\nTo: %s\r\n\r\n%s' % (user.email, letter))

	else:
		print "--- %s" % user.username

