#!/usr/bin/env python

from core.models import *

piratar = Polity.objects.get(id = 1)
members = piratar.members.all()
users = User.objects.all()

broken_users = []
for user in users:
	if user not in members:
		broken_users.append(user)

if len(broken_users) > 0:
	for broken_user in broken_users:
		print "Broken user: %s, name '%s', email '%s'" % (user.username, user.get_profile().displayname, user.email)
else:
	#print "No broken users!"
	pass

