# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skills',
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(to='tasks.TaskSkills'),
        ),
    ]
