# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_duration_weeks',
            field=models.IntegerField(default=1, verbose_name='Estimated number of weeks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours_per_week',
            field=models.IntegerField(default=1, verbose_name='Estimated hours per week'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_recruiting',
            field=models.BooleanField(default=True, verbose_name='Is recruiting'),
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteers_needed',
            field=models.IntegerField(default=1, verbose_name='Number of volunteers needed'),
        ),
    ]
