# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180119_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCategories',
            new_name='TaskCategory',
        ),
        migrations.RenameModel(
            old_name='TaskSkills',
            new_name='TaskSkill',
        ),
    ]
