# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskrequest_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='objectives',
            field=models.CharField(max_length=200, verbose_name='Objectives'),
        ),
    ]
