# Generated by Django 2.2.6 on 2019-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190822_2006'),
        ('tasks', '0007_task_require_phone'),
    ]

    operations = [
    ]
