# Generated by Django 2.2.25 on 2022-02-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_20191019_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
    ]
