# Generated by Django 2.2.4 on 2019-08-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0002_auto_20181207_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polity_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='polity',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='polity',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent polity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polity.Polity'),
        ),
    ]
