# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0003_polity_require_phone_for_volunteering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polity',
            name='require_phone_for_volunteering',
        ),
    ]
