# Generated by Django 2.2.6 on 2019-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0004_remove_polity_require_phone_for_volunteering'),
        ('polity', '0003_auto_20190822_2006'),
    ]

    operations = [
    ]
