# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.timezone import timedelta

fieldnames = [
    'issue_discussion_time',
    'issue_proposal_time',
    'issue_vote_time',
]


def convert_integers_to_durations(apps, schema_editor):
    PolityRuleset = apps.get_model('polity', 'PolityRuleset')

    def type_convert(seconds):
        minutes, seconds = divmod(seconds, 60)
        hours, minutes = divmod(minutes, 60)
        return hours, minutes, seconds

    for ruleset in PolityRuleset.objects.all():
        for fieldname in fieldnames:
            hours, minutes, seconds = type_convert(getattr(ruleset, fieldname).microseconds)
            setattr(ruleset, fieldname,  timedelta(hours=hours, minutes=minutes, seconds=seconds))

        ruleset.save()


def dummy_function(apps, schema_editor):
    PolityRuleset = apps.get_model('polity', 'PolityRuleset')

    for ruleset in PolityRuleset.objects.all():
        for fieldname in fieldnames:
            field = getattr(ruleset, fieldname)
            setattr(ruleset, fieldname, field.total_seconds())

        ruleset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0005_polity_wranglers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polityruleset',
            name='issue_discussion_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='polityruleset',
            name='issue_proposal_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='polityruleset',
            name='issue_vote_time',
            field=models.DurationField(),
        ),
        migrations.RunPython(
            convert_integers_to_durations,
            dummy_function
        ),
    ]
