# Generated by Django 2.2.7 on 2020-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0005_merge_20191019_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polity',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='polity',
            name='order',
            field=models.IntegerField(default=1, help_text='Optional, custom sort order. Polities with the same order are ordered by name.', verbose_name='Order'),
        ),
    ]
