# Generated by Django 3.1.5 on 2021-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0007_polity_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='polity_type',
            field=models.CharField(choices=[('U', 'Unspecified'), ('S', 'Regional group'), ('C', 'Constituency group'), ('I', 'Special Interest Group')], default='U', max_length=1),
        ),
    ]
