# Generated by Django 3.1.5 on 2021-01-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0008_polity_polity_type'),
        ('polity', '0008_polity_eligibles'),
    ]

    operations = [
    ]
