# Generated by Django 3.1.5 on 2021-01-18 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polity', '0009_merge_20210118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='eligibles',
            field=models.ManyToManyField(blank=True, related_name='polities_eligible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='polity',
            name='name_short',
            field=models.CharField(blank=True, default='', help_text='Optional. Could be an abbreviation or acronym, for example.', max_length=30, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='polity',
            name='polity_type',
            field=models.CharField(choices=[('U', 'Unspecified'), ('R', 'Regional group'), ('C', 'Constituency group'), ('I', 'Special Interest Group')], default='U', max_length=1),
        ),
    ]
