# Generated by Django 3.1.5 on 2021-01-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polity', '0010_auto_20210118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='polity_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('regional', 'Regional Group'), ('constituency', 'Constituency Group'), ('special_interest', 'Special Interest Group')], default='unspecified', max_length=20),
        ),
    ]
